package com.chat.googleapi.app.module.apple;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppleLoginUtilsTest {

    @Test
    void verifyToken() {
        AppleLoginUtils.verifyToken("eyJraWQiOiJCaDZIN3JIVm1iIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiY29tLmV4YW1wbGUuZmxpcnRlci5kYmciLCJleHAiOjE3MTE0MjY0MTksImlhdCI6MTcxMTM0MDAxOSwic3ViIjoiMDAxOTIwLjcwZGM3N2M0YTNjMjRhMjRiMjM1ZGQ3ZTJlMDhmMjQzLjA4MDEiLCJjX2hhc2giOiJJV0JWMkk1MEg4aGd2aHpaY0p4MTRnIiwiZW1haWwiOiJ6aG91emhlbmxpYW5ncHBAMTYzLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhdXRoX3RpbWUiOjE3MTEzNDAwMTksIm5vbmNlX3N1cHBvcnRlZCI6dHJ1ZX0.juzHRACyePN_mBrnRfQcOs0Fr3oZcFwYeHdfSEwsY6t4wK1EQSgk7PfdDgdtZDxsdK8R6SinoBq5df84ucEjZfdXMaRU0j0Vvo-8-MJ1plDhOJq45lHdKb8lezs9SrqYG637gqfB3D9rq_EZNbG8_U9I1qoIKurpfQgB8TvQNx98S7RhzXeiRsureikEkLwGbAd1B0FvDcRGm9fjwzSm08_pjKtXecxEYK6PFisuLcY0i76YyBNWMdq4DeGsMg783TwreaKkhuZicWC3LQ8NueErlOe3iav_XLjg_PC_6mdATj3MQuXkwldAAEw0lPaLY2FGjQSFA-ro75Glvt_aXg");
    }
}